#!/bin/sh
set -eu

REMOTE_HOST="${CCE_REMOTE_HOST:-colossus}"
REMOTE_DIR="${CCE_REMOTE_DIR:-/Users/kevinmattice/cce}"
CONFIG_PATH="${CCE_CONFIG_PATH:-config/cce.json}"

ssh "$REMOTE_HOST" "
  cd '$REMOTE_DIR'
  if [ -x '$REMOTE_DIR/.venv/bin/python' ]; then
    PYTHON_BIN='$REMOTE_DIR/.venv/bin/python'
  elif [ -x /opt/homebrew/bin/python3 ]; then
    PYTHON_BIN=/opt/homebrew/bin/python3
  else
    PYTHON_BIN=\$(command -v python3)
  fi
  pkill -f 'gateway.runtime --config $REMOTE_DIR/$CONFIG_PATH' || true
  nohup \"\$PYTHON_BIN\" -m gateway.runtime --config '$REMOTE_DIR/$CONFIG_PATH' > '$REMOTE_DIR/runtime/gateway.stdout.log' 2>&1 &
  sleep 2
  echo \"Python: \$PYTHON_BIN\"
  ps -ef | grep 'python.*gateway.runtime' | grep -v grep
  tail -n 10 '$REMOTE_DIR/runtime/gateway.stdout.log'
"
